language: python

python:
  - 2.7
  - 3.2
  - 3.3

install:
  - '2.7'
  - '3.2'
  - '3.3'

env:
  - TOXENV="py27"
  - TOXENV="py32"
  - TOXENV="py33"

install:
  - "pip install tox"
  - "pip install coveralls"

script:
  - tox -e $TOXENV
  - coverage run --source=cdek setup.py test

after_success:
  - coveralls